title: "CTIV 5057: Introduction to GPT & LLMs in Clinical & Translational Research"
description: "Jan. 27, 2025 - April 7, 2025, 3:30-4:45 pm East Time on Mondays | 
              Remote"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
